jk- create listPage
ucsb-cs156-w22/team04-w22-6pm-HappyCows pull request #40
Opened 2022-03-08 01:11 UTC by Jacqueskim

# Overview

Modified the CommonTable and implmented the list page for commons and the test. Also modified the stories, App.js, NavBar.js for listpage.

# Issues Addressed

Test still needs to be implmented for CommonsTable

# Details

https://github.com/ucsb-cs156-w22/team04-w22-6pm-HappyCows/issues/12

2022-03-08 22:23 UTC, pconrad requested changes, later dismissed
It seems there are some code coverage problems ... they are pointed out by the codecov comments on the PR. 

See if you can address these.

2022-03-09 06:02 UTC, DannyCoco approved these changes, later dismissed

2022-03-10 01:09 UTC, kheff16 commented
needs update with main branch as a merge or a rebase. it looks like you addressed Phill's concern, so this otherwise lgtm

2022-03-10 03:30 UTC, rsdharmaji submitted a review, later dismissed
LGTM, the date works perfectly now!

2022-03-10 20:30 UTC, jacksoncooper commented
I just realized the `Date` constructor that accepts a string does an implicit conversion from your browser's local time to UTC. That's really bad, because the backend doesn't store time zone information. There are two things this affects.

- Displaying the date in the form with `Date.toLocaleString`.
- The form itself. The tests make it appear that `react-hook-form` results in a `Date` object.

And shortly, the edit page.

2022-03-11 04:55 UTC, pconrad approved these changes, later dismissed
LGTM.. though I will want to test on Heroku before merging

2022-03-11 05:24 UTC, jacksoncooper reviewed
Just for documentation. I'm not going to argue against a merge; we can address these concerns as a whole when the edit page is merged, which has similar problems.

2022-03-11 05:24 UTC, jacksoncooper commented on frontend/src/main/components/Commons/CommonsTable.js
> +    }
Here's one implicit conversion from the browser's local time to UTC; the displayed dates don't make sense. We're better off avoiding `Date` and writing and displaying our own type.

2022-03-11 05:24 UTC, jacksoncooper commented on frontend/src/tests/components/Commons/CreateCommonsForm.test.js
> +      startingDate: new Date("2021-01-01"),
This line is what makes me think `react-hook-form` passes a `Date` object to `onSubmit`. I thought it would just be the value of the HTML date input.

2022-03-11 05:24 UTC, jacksoncooper commented on frontend/src/tests/pages/AdminCreateCommonsPage.test.js
> +        // POST contains the suffix .000Z, which Java's LocalDateTime.parse ignores. [1]
This was before I realized what `Date` was up to.

2022-03-11 06:53 UTC, jacksoncooper approved these changes, later dismissed
Excepting my nonsensical use of `Date.toLocaleString`, this is good.

2022-03-12 02:29 UTC, jacksoncooper submitted a review, later dismissed
Reverted date conversion and button columns.

2022-03-12 02:32 UTC, sahilnaik1 approved these changes, later dismissed
LGTM

2022-03-12 04:06 UTC, jacksoncooper approved these changes
Now with 📕.

2022-03-12 05:32 UTC, merged