RL-SM: Add Fuctionality for onBuy, onSell Buttons, updating totalWealth using 2 PUT endpoints
ucsb-cs156-w22/team04-w22-6pm-HappyCows pull request #51
Opened 2022-03-11 00:21 UTC by Lin2

# Overview
We added two PUT endpoints for BUY and SELL, and created onBuy and onSell basic functionality to update totalWealth of a user on the Playpage.

# Issues Addressed
 We addressed some of the points in #15 . This issue isn't completed yet however, but we wanted to get a PR in for CI/CD.

# Details

2022-03-11 05:49 UTC, pconrad requested changes
Where are the controller tests for the new methods?

2022-03-11 08:02 UTC, Lin2 commented
> Where are the controller tests for the new methods?

I realized we were missing this right after we made the request -- working on it now!

2022-03-11 13:08 UTC, Lin2 commented
> **02 Frontend 03 Mutation Testing (JavaScript/Stryker, testing the test suite) / build (17.x) (pull_request) ** In progress — This check has started...

The PR has been completed with controller tests for UserCommonsController.

2022-03-12 05:26 UTC, eambriz27 submitted a review, later dismissed
Looks like you have some merge conflicts to resolve, but everything else LGTM!

2022-03-12 22:39 UTC, pconrad requested changes
Couple of "TODOs left in the code"...

2022-03-12 22:39 UTC, pconrad commented on src/test/java/edu/ucsb/cs156/happiercows/controllers/UserCommonsControllerTests.java
> +    MvcResult response = mockMvc.perform(put("/api/usercommons/buy?id=1") //oof, accidentally made PUT endpoints id variable instead of commonsId. TODO: Fix later.
Fix now maybe?

2022-03-12 22:39 UTC, pconrad commented on src/test/java/edu/ucsb/cs156/happiercows/controllers/UserCommonsControllerTests.java
> +
As long as we are fixing things, maybe this white space too...

2022-03-12 22:39 UTC, pconrad commented on src/test/java/edu/ucsb/cs156/happiercows/controllers/UserCommonsControllerTests.java
> +    MvcResult response = mockMvc.perform(put("/api/usercommons/buy?id=234") //oof, accidentally made PUT endpoints id variable instead of commonsId. TODO: Fix later.
oof indeed :-)

2022-03-13 01:55 UTC, eambriz27 submitted a review, later dismissed
LGTM

2022-03-15 06:14 UTC, Lin2 commented
Bad PR

2022-03-15 06:14 UTC, closed without merging